### ISSUE TITLE
当页面过小时，布局混乱

### ISSUE THREAD

**Issue by Brs-sss** [Brs-sss/Growth-Snap#108]
很多页面在手机机型
目前出现该问题的页面有：
1. show页面
2. event和text上传页面
3. 创建计划页面
4. 详细计划页面
（其中2和4是出现字体过小的情况，排班不乱但字体很小，难以阅读）
建议：如非必要，在设置height和字体时采用绝对值（px等）。

**Comment by whw-alex** [comment]
已优化
